## 1. Numpy 모듈 불러오기:

In [1]:
import numpy as np   #numpy패키지 불러옴
np.__version__       #현재 설치된 numpy버전

'1.16.5'

## 2. 배열생성:

In [2]:
arr1 = np.array([1,3,5,7,9])   #리스트 사용해 배열 생성
arr2 = np.array((1,3,5,7,9))   #튜플 사용해 배열 생성
type(arr1)

numpy.ndarray

In [3]:
arr3 = arr1     #이렇게 바로 대입하면 오류날 수도 

In [4]:
id(arr1)       

2476352450768

In [5]:
id(arr3)        #id(arr1)과 값이 같음 => arr1과 arr3는 메모리 공간 공유

2476352450768

In [6]:
arr4 = arr1.copy()   #copy()사용해 대입해야 오류안남

In [7]:
id(arr1)   

2476352450768

In [8]:
id(arr4)      #id(arr1)와 값이 다름 => 완전히 다른 객체

2476352491968

## 3. 메서드

### 3.1 arange 메서드:

In [9]:
np.arange(10)     #0~9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)   #10~19

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10, 20, 3)   #10~19까지 3씩 뜀

array([10, 13, 16, 19])

In [12]:
arr = np.arange(10) 

In [13]:
len(arr)    #리스트와 같음

10

In [14]:
arr.size    #원소개수  #리스트에서는 사용 불가능  #numpy배열에서만 가능

10

### 3.2 linspace 메서드:

- (시작, 끝, 데이터개수)

In [15]:
np.linspace(1, 10, 5)    #np.linspace(시작, 끝, 데이터개수)
                         #1~10까지 5개 데이터 생성
                         #데이터 개수를 지정하지 않으면 기본값 50

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
arr = np.linspace(0, 10, 5, retstep=True)
type(arr)

tuple

In [17]:
arr[0]

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
arr[1]

2.5

### 3.3 zeros 메서드:

In [19]:
np.zeros(10)      #모든 원소가 0이고, 데이터가 10개인 행

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,4))   #0을 원소로 하는 3*4행렬

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.zeros(5, dtype ='int64')  #모든 원소가 0이고, 데이터가 5개인 행   #64비트 정수타입

array([0, 0, 0, 0, 0], dtype=int64)

In [22]:
np.zeros(5, dtype ='int64').dtype   #np.zeros의 타입  

dtype('int64')

### 3.4 ones 메서드:

In [23]:
arr = np.ones((2,3), dtype ='int_')  #1을 원소로하는 2*3행렬   

In [24]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

## 4. 타입

### 4.1 타입변환:

In [25]:
arr.dtype     #32비트 정수타입

dtype('int32')

In [26]:
arr.astype('float32')    #str_arr.astype(dtype)   
                         #지정한 dtype형태로 타입 변환

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

### 4.2 원소의 자료형은 일치되어야 한다:

In [27]:
arr1 = np.array([111, 2.3,  True, False, False])    #숫자형, bool원소 혼재
arr1                                                #숫자형으로 자동 변환

array([111. ,   2.3,   1. ,   0. ,   0. ])

In [28]:
arr2 = np.array([111, 2.3, 'python', 'abc'])    #숫자형과 문자열 혼재
arr2                                            #문자열로 자동변환

array(['111', '2.3', 'python', 'abc'], dtype='<U32')

In [29]:
arr3 = np.array([111, True, 'abc'])   #숫자형, 문자열, 불 원소 혼재
arr3                                  #문자열로 자동변환

array(['111', 'True', 'abc'], dtype='<U11')

## 5. 인덱싱과 슬라이싱

### 5.1 Numpy 배열의 인덱싱: 위치나 조건 지정해 원소 선택

In [30]:
a = np.array([1, 2, 3, 4, 5])
a[2]      #세번째 원소

3

In [31]:
a[-1]     #끝에서 첫번째 원소

5

In [32]:
a[:]     #전체 원소 

array([1, 2, 3, 4, 5])

### 5.2 Numpy 배열의 슬라이싱: 범위 지정해 원소 선택

In [33]:
a = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])    #3*3행렬
a                                                  

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
a[1]    #1행 전체(행위치만 지정하면 행전체 출력)

array([4, 5, 6])

In [35]:
a[-1]   #마지막에서 첫번째 행

array([7, 8, 9])

In [36]:
a[:2]    #0~1행

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a[2][1]   #2행 1열에 위치한 원소

8

In [38]:
a[2,1]    #2행 1열에 위치한 원소

8

In [39]:
a[[0,2]]    #0행, 2행

array([[1, 2, 3],
       [7, 8, 9]])

In [40]:
a[1:,1:]    #[행 시작:행 끝, 열 시작:열 끝]
            #1~2행, 1열~2열

array([[5, 6],
       [8, 9]])

## 6. 배열

### 6.1 Numpy 배열의 모양:

In [41]:
a.size    #원소의 개수

9

In [42]:
a.shape   #모양 m*n

(3, 3)

In [43]:
a.ndim    #몇 차원인지

2

In [44]:
a = np.arange(15)    #0~14
a.reshape(3,5)       #3*5모양의 2차원 행렬로 바꿔서 보여줌(비항구적-변함)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
a   #비항구적이라 리스트로 나옴

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
a.shape=(3,5)     #3*5모양의 2차원 행렬로 바꿔줌(항구적-변하지않음)
a                 #항구적이라 행렬로 바뀜

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 6.2  Numpy 배열의 모양 (주의):

In [47]:
a = np.array([2,5,1,3])
a.shape       #rank 1 배열 , 벡터아님

(4,)

In [48]:
a = a.reshape((4,1))   #칼럼 벡터
a

array([[2],
       [5],
       [1],
       [3]])

In [49]:
a.shape

(4, 1)

In [50]:
a = np.arange(10)    #0~9 
b = a.reshape(2,5)   #2*5모양의 2차원 행렬로 바꿔서 보여줌
a[0] = -999   

In [51]:
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [52]:
b       #직접 대입해서 메로리 공간 공유

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [53]:
c = a.reshape(2,5).copy()    #얕은 복사로 새로운 객체 만듬
c[0,0] = 0                   #copy()사용해 메모리 공간이 달라 아무 영향없음
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

### 6.3 Numpy 로직 배열과 fancy indexing:

In [54]:
arr = np.arange(100)             #0~99
arrMask = ( (arr % 5) == 0 )     #로직배열, 5의 배수이면 True
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [55]:
arrMask = ( ( (arr % 5) == 0 )  & ( arr >0) )  #로직배열, 0이상의 5의 배수이면 True
arr[arrMask]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

### 6.4 Numpy 배열의 확장: append, axis 사용

- 리스트는 append나 더하기로 확장

- numpy는 더하기가 안되므로 append사용해서 확장해야 함

- 2,3차는 axis로 확장

In [56]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])   #맨 마지막에 추가
b

array([1, 2, 3, 4, 5, 6])

In [57]:
a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[9, 9]], axis=0)      #새로운 행으로 추가 - 비항구적(변함)
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [58]:
c = np.append(a, [[9], [9]] , axis=1)   #새로운 열로 추가 - 비항구적(변함)
c

array([[1, 2, 9],
       [3, 4, 9]])

### 6.6 Numpy 배열의 삭제:

In [59]:
a = np.array([[1, 2, 3],[4, 5, 6]])
np.delete(a, 0)             #원소 하나 삭제 - 비항구적(변함)

array([2, 3, 4, 5, 6])

In [60]:
np.delete(a, (0, 2, 4))

array([2, 4, 6])

In [61]:
np.delete(a, 0, axis = 0)   #행 전체 삭제 - 비항구적(변함)

array([[4, 5, 6]])

In [62]:
np.delete(a, 1, axis = 1)  #열 전체 삭제 - 비항구적(변함)

array([[1, 3],
       [4, 6]])