### 1.1 리스트에서 + 연산자 : 연결

In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]

In [3]:
a + a      #리스트에서 +는 연결

[1, 2, 3, 1, 2, 3]

### 1.2 Numpy에서 + 연산자 : 원소별 더하기

In [4]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [5]:
a+b       #numpy배열에서 +는 원소별 더하기

array([5, 7, 9])

### 2.1 리스트에서 * 연산자 : 반복 횟수

In [6]:
a = [1, 2, 3]

In [7]:
3*a    #리스트에서 *는 반복횟수

[1, 2, 3, 1, 2, 3, 1, 2, 3]

### 2.2 Numpy에서 * 연산자 : 원소별 곱하기

In [8]:
b = np.array([1, 2, 3])

In [9]:
3*b     #numpy에서 *는 원소별 곱하기

array([3, 6, 9])

In [10]:
np.array(3*[1,2,3])   #123 123 123

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [11]:
np.tile(b,3)   #123 123 123

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [12]:
np.repeat(b, 3)   #111 222 333

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### 2.3 Numpy 배열의 연산: 계산 하는 것

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [14]:
a+b

array([5, 7, 9])

In [15]:
a-b

array([-3, -3, -3])

In [16]:
a*b

array([ 4, 10, 18])

In [17]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

### 3.1 universal function: 원소별 연산해서 또다른 배열을 만듬

In [18]:
x = np.array([0, 1, 2, 3, 4, 5])

In [19]:
x**3

array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [20]:
np.sqrt(x)     

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [21]:
np.exp(x)       #지수

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [22]:
np.cumsum(x)    #누적 합: univrsal function아님

array([ 0,  1,  3,  6, 10, 15], dtype=int32)

### 3.2 Numpy가 제공하는 함수: universal function아님(결과가 숫자하나)

In [23]:
np.random.seed(123)  #seed는 랜덤숫자 초기화(같은 조건에서 같은결과나오는지 보기위함)
a = np.random.randint(1, 11, size=1000)

In [24]:
np.unique(a)     #고유 값 (개수아님)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.median(a)

5.0

In [26]:
np.sum(a)

5485

In [27]:
np.round(np.var(a),2)

8.19

In [28]:
np.round(np.mean(a),2)

5.48

In [29]:
np.round(np.std(a),2)

2.86

In [30]:
np.max(a)

10

In [31]:
np.min(a)

1

### 3.3 배열의 메서드로 제공되는 함수:

In [32]:
x=np.arange(1,11)

In [33]:
x.sum()

55

In [34]:
x.mean()

5.5

In [35]:
x.std()    #표준편차

2.8722813232690143

In [36]:
x.var()    #분산

8.25

In [37]:
x.cumsum()  #누적 합

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [38]:
y = np.arange(1,10)
y = y.reshape((3,-1))    #(3,-1)은 (3*3)과 같음
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
print(y.mean(axis=0))    #열의 평균

[4. 5. 6.]


In [40]:
print(y.mean(axis=1))    #행의 평균

[2. 5. 8.]


In [41]:
z = np.random.randint(10,size=1000)    #0~9까지의 랜덤숫자를 가지고 1000개의 배열 만듬

In [42]:
z.max()

9

In [43]:
z.min()

0

In [44]:
(z > 5).sum()   #True면 1로 계산

392

In [45]:
np.unique(z)    #원소 값을 가져옴(개수아님)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
sorted(set(z))   #랜덤함수 돌리고 나서 중복을 없애고 싶다면 set에 넣으면 됨

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [47]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [48]:
a.argmax()   #어느 위치에서 제일 높은 값이 나오는지 알고 싶을 때
             #배열에서 최댓값의 인덱스(위치)

4

In [49]:
a.argmin()   #어느 위치에서 제일 낮은 값이 나오는지 알고 싶을 때
             #배열에서 최솟값의 인덱스(위치)

1