**1. 스칼라는 하나의 수치(숫자) : 3, 4.5343, 98**

**2. 벡터는 배열의 형태 : (1,2,3)**


#### 벡터의 원소별 덧셈, 뺄셈, 곱셈 => 또다른 배열의 형태로 나옴

- (1,2,3)+(1,2,3) = (2,4,6)



#### 벡터의 내적(곱해서 더함) => 하나의 숫자(스칼라)로 결과가 나옴

- (1,2,3)*(1,2,3) = 32

- NumPy dot메서드 또는 함수를 사용해 계산

In [2]:
import numpy as np

## 1. 벡터의 연산:

In [2]:
x = np.array([1, 3, 5])   #길이가 3인 배열
y = np.array([2, 4, 6])   #길이가 3인 배열
x+y                       #numpy에서 +는 원소별 더하기


array([ 3,  7, 11])

In [3]:
x-y   

array([-1, -1, -1])

In [4]:
x*y  

array([ 2, 12, 30])

In [5]:
np.dot(x,y)     #내적 (곱한뒤 합함)

44

In [6]:
x.dot(y)        #내적이므로 y.dot(x)해도 같은 결과 나옴

44

In [7]:
y.dot(x)       

44

### dot 연산:

In [8]:
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])
x = x.reshape((3,1))
y = y.reshape((1,3))
print("{}".format(x))
print(" ----------")
print("{}".format(y))

[[1]
 [3]
 [5]]
 ----------
[[2 4 6]]


In [9]:
y.dot(x)[0,0]

44

In [10]:
x.dot(y)

array([[ 2,  4,  6],
       [ 6, 12, 18],
       [10, 20, 30]])

## 2. 행렬 만들기:

In [11]:
np.zeros((2,3))   #0을 원소로 하는 행렬    #안에는 튜플 들어가야함

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2,3))    #1을 원소로 하는 행렬    #안에는 튜플 들어가야 함

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.random.seed(222)          #seed는 랜덤숫자 초기화(같은 조건에서 같은결과나오는지 보기위함)
np.random.random((2,2))      #0과 1사이 균등분포 랜덤행렬, 튜플 두겹
                             #균등분포(0~1사이 일정간격으로 특정값 생성)

array([[0.52602843, 0.68531719],
       [0.83567419, 0.65376526]])

In [14]:
np.random.seed(111)      #랜덤숫자 초기화
np.random.randn(2,2)     #정규분포 랜덤 행렬, 튜플 한겹

array([[-1.13383833,  0.38431919],
       [ 1.49655378, -0.3553823 ]])

In [15]:
m=np.diag([1,2,3])    #대각행렬-대각선원소를 가진 행렬
m

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
np.diag(m)    #행렬에서 대각선원소만 뽑아오기

array([1, 2, 3])

## 3. 행렬의 연산

### 3.1 행렬과 행렬: +와  -

In [17]:
m1 = np.array([[1, 2, 3],[4, 5, 6]])  #리스트안에 리스트를 사용해서 행렬 만들 수 있음
m2 = np.array([[6, 5, 4],[3, 2, 1]])

In [18]:
m1+m2

array([[7, 7, 7],
       [7, 7, 7]])

### 3.2 행렬과 행렬: *와 dot

In [19]:
m1*m2   #행렬의 곱은 *가 아니라 dot임  #왼쪽행렬 열의 수 = 오른쪽행렬 행의 수

array([[ 6, 10, 12],
       [12, 10,  6]])

In [20]:
np.dot(m1, m2)    #사이즈 오류 발생 (왼쪽행렬 열의 수 = 오른쪽행렬 행의 수)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [21]:
np.transpose(m2)  #열의수와 행의수를 맞추기위해 전치행렬 사용

array([[6, 3],
       [5, 2],
       [4, 1]])

In [22]:
np.dot(m1,np.transpose(m2))  #전치행렬로 사이즈 변경한 후, 사이즈 오류 안남

array([[28, 10],
       [73, 28]])

In [23]:
x=np.array([1,3,5])  #길이가 3인 배열
y=np.array([2,4,6])  
print(x)
print(y)

[1 3 5]
[2 4 6]


### 3.3 스칼라와 행렬: 곱, 나누기

In [3]:
m = np.array([[1, 2],[3, 4]])

In [4]:
m*3    #스칼라와 행렬의 곱

array([[ 3,  6],
       [ 9, 12]])

In [5]:
m/2   #행렬을 스칼라로 나눔

array([[0.5, 1. ],
       [1.5, 2. ]])

In [6]:
m+1

array([[2, 3],
       [4, 5]])

## 4. shape와 reshape 구분하기

#### shape

- x를 numpy배열로 만들고 y를 numpy배열로 만들었을 떄  x.shape하면 3이 나오는데 이건 사이즈임

- shape는 가로세로 보여주는거
- (3, ), (  ,3)
- x,y는 가로도 세로도 아닌 길이만 있는 벡터라는 뜻

##### reshape


- reshape해서 강제로 가로행렬, 세로행렬을 만듬

- 하나의 행을 갖는 행벡터, 하나의 열을 갖는 열벡터로 강제로 만든거임

- reshape((-1,3))하면 한쪽방향 크기에 맞게 나머지 크기 자동맞춤

- -1하고 3을 입력하고 15가 나오게하면 5크기가 맞춰짐


In [24]:
x=x.reshape((3,1))   #열 벡터 3*1행렬   #튜플 들어감
print(x)

[[1]
 [3]
 [5]]


In [25]:
y=y.reshape((1,3))   #행 벡터 1*3행렬   #튜플 들어감
print(y)

[[2 4 6]]


In [26]:
y.dot(x)  #행렬의 곱  #x.dot(y)와 같음
          #결과는 하나의 원소를 갖는 행렬로 나옴: 스칼라 44가 아닌 행렬 44임

array([[44]])

In [27]:
y.dot(x)[0,0]

44

## 5. 역행렬:

In [32]:
m = np.array([[1, 2],[3, 4]])   #정사각형 모양의 행렬
minv = np.linalg.inv(m)         #m의 역행렬
minv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [33]:
mres = np.dot(m, minv)    #행렬의 곱
np.round(mres,2) 

array([[1., 0.],
       [0., 1.]])

## 6. 연립 방정식 (선형 방정식의 개수 = 미지수의 개수인 경우):

- 두명의 작업자가 생산에 투입되는 상황 가정
- x가 5시간 작업에 투입, y가 8시간 작업에 투입되니 생산량은 30
- 5x + 8y = 30
- x가 6시간 작업에 투입, y가 4시간 작업에 투입되니 생산량은 25
- 6x + 4y = 25
- 작업자들의 시간당 생산량을 구하기 = > 역행렬 사용

In [34]:
A = np.array([[5, 8],[6, 4]])   #정사각형 모양의 행렬
b = np.array([[30], [25]])
Ainv = np.linalg.inv(A)         #A의 역행렬
print(np.dot(Ainv,b))           #해

[[2.85714286]
 [1.96428571]]


- x의 시간당 생산량
- y의 시간당 생산량

In [35]:
np.linalg.solve(A, b)   

array([[2.85714286],
       [1.96428571]])