## 1. 배열 생성하기

### 1) 시퀀스 데이터로 배열 생성 (주로 리스트 사용) 

#### 1차원 배열

In [1]:
import numpy as np   # NumPy 불러오기

In [2]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)       # array()의 인자로 리스트 데이터를 넣어 배열 생성
                           # obj=np.array(seq_data)
a1

array([0, 1, 2, 3, 4, 5])

In [3]:
a1.dtype     # 32비트 정수타입 

dtype('int32')

In [4]:
np.array([0.5, 2, 0.01, 8])   # array()에 리스트 데이터를 직접 넣어 배열 생성도 가능

array([0.5 , 2.  , 0.01, 8.  ])

#### 2차원 배열

In [5]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 2) 범위를 지정해 배열 생성


#### 1차원 배열

In [6]:
np.arange(0, 10, 2)   # np.arrange(시작, 끝, 스텝)

array([0, 2, 4, 6, 8])

In [7]:
np.arange(1, 10)      # 스텝이 1인 경우 생략가능
                      # np.arrange(시작, 끝)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(5)         # 스텝이 1이고, 시작이 0인 경우 생략가능
                     # np.arrange(끝)

array([0, 1, 2, 3, 4])

#### 2차원 배열

In [9]:
np.arange(12).reshape(4,3)   # 12개의 숫자를 생성 후, 4*3행렬 만듬
                             # 1차원배열에 .reshape(m,n) 추가하면 m*n 형태의 2차원 행렬로 변경
                             # arrange()원소 개수와 m*n수는 같아야 오류가 안남

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
b1 = np.arange(12).reshape(4,3)     
b1.shape   # 배열의 형태 알기

(4, 3)

- m*n(2차원 배열)이므로 (m,n)출력

In [11]:
b2 = np.arange(5)
b2.shape   # 배열의 형태 알기

(5,)

- n개의 요소를 갖는 1차원 배열은 (n,)으로 출력

### 3) 시작, 끝, 데이터 개수 지정해 배열 생성

In [12]:
np.linspace(1, 10, 10)   # np.linspace(시작, 끝, 데이터개수)
                         # 1~10까지 10개 데이터 생성
                         # 데이터 개수를 지정하지 않으면 기본값 50

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### 4) 모든 원소가 0이거나 1인 배열 생성

In [13]:
np.zeros(10)      # 모든 원소가 0이고, 데이터 10개인 1차원 배열

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4))   # 모든 원소가 0인 3*4 2차원 배열

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(5)        # 모든 원소가 1이고, 데이터 5개인 1차원 배열

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,5))    # 모든 원소가 1인 3*5 2차원 배열

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 5) 단위행렬 생성

In [17]:
np.eye(3)         # 3*3 단위행렬
                  # 정사각형 행렬, 주 대각선이 1, 나머지는 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 6) 배열의 데이터 타입 변환

In [18]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])     # 문자열 데이터이므로 연산을 위해 숫자열로 변환해야 함
num_a1 = str_a1.astype(float)     # num_arr=str_arr.astype(dtype)   
                                  # 지정한 dtype형태로 타입 변환
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

### 7) 난수 배열의 생성

#### 실수 난수

In [19]:
np.random.rand(2,3)         # np.random.rand()
                            # 2*3의 2차원 배열의 실수 난수 생성

array([[0.57849387, 0.04225414, 0.69356647],
       [0.70442364, 0.52624383, 0.183161  ]])

In [20]:
np.random.rand()     # 인자가 없으면 임의의 실수 난수 하나 생성

0.6416460541533797

In [21]:
np.random.rand(2,3,4)      # 3*4행렬이 2개 생성
                           # 리스트가 2개임  #서로 감싸고 있음

array([[[0.14270053, 0.76207633, 0.27694602, 0.32566051],
        [0.95632506, 0.44903968, 0.37144705, 0.05158398],
        [0.9112231 , 0.88925955, 0.85919148, 0.22622168]],

       [[0.22114456, 0.13820153, 0.52990352, 0.0602223 ],
        [0.21853623, 0.29578854, 0.53695544, 0.14622146],
        [0.62957426, 0.17949361, 0.1716999 , 0.30751803]]])

#### 정수 난수

In [22]:
np.random.randint(10, size=(3, 4))   # np.random.randint(low, high, size)
                                     # low가 입력되지 않으면 0
                                     # size는 배열의 형태
                                     # size가 입력되지 않으면 기본값 1

array([[8, 9, 6, 8],
       [1, 8, 9, 4],
       [7, 6, 9, 5]])

In [23]:
np.random.randint(1, 30)       # 1~30 중 정수 난수
                               # size 입력되지 않았으므로 배열 1형태

6

## 2. 배열의 연산

### 1) 기본 연산

- 1차원의 경우 원소개수가 같고, 2차원의 경우 m과 n이 같아야 연산가능

In [24]:
arr1 = np.array([10, 20, 30, 40])   # 원소 개수가 같은 1차원 배열 생성
arr2 = np.array([1, 2, 3, 4])

In [25]:
arr1 + arr2

array([11, 22, 33, 44])

In [26]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [27]:
arr2*2

array([2, 4, 6, 8])

In [28]:
arr2**2

array([ 1,  4,  9, 16], dtype=int32)

In [29]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [30]:
arr1 / arr2

array([10., 10., 10., 10.])

In [31]:
arr1 / (arr2**2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [32]:
arr1 > arr2     # 비교 연산도 가능

array([ True,  True,  True,  True])

### 2) 통계를 위한 연산

In [33]:
arr3 = np.arange(5)    # 배열 생성
arr3

array([0, 1, 2, 3, 4])

In [34]:
[arr3.sum(), arr3.mean()]   # 합과 평균

[10, 2.0]

In [35]:
[arr3.std(), arr3.var()]    # 표준편차와 분산

[1.4142135623730951, 2.0]

In [36]:
[arr3.min(), arr3.max()]    # 최솟값과 최댓값

[0, 4]

In [37]:
arr4 = np.arange(1,5)   # arr3은 원소에 0이 있어 누적 곱이 0이 되니 새로운 배열 생성
arr4

array([1, 2, 3, 4])

In [38]:
arr4.cumsum()     # 누적 합    
                  # [1,1+2,1+2+3,1+2+3+4]

array([ 1,  3,  6, 10], dtype=int32)

In [39]:
arr4.cumprod()         # 누적 곱
                       # [1,1*2,1*2*3,1*2*3*4]

array([ 1,  2,  6, 24], dtype=int32)

### 3) 행렬 연산

In [40]:
A = np.array([0, 1, 2, 3]).reshape(2,2)    # A행렬 생성
A

array([[0, 1],
       [2, 3]])

In [41]:
B = np.array([3, 2, 0, 1]).reshape(2,2)    # B행렬 생성
B

array([[3, 2],
       [0, 1]])

In [42]:
A.dot(B)        # 행렬 곱

array([[0, 1],
       [6, 7]])

In [43]:
np.dot(A,B)     # 행렬 곱

array([[0, 1],
       [6, 7]])

In [44]:
A.transpose()    # 전치행렬(행이 열이 되고, 열이 행이되는)

array([[0, 2],
       [1, 3]])

In [45]:
np.transpose(A)  # 전치행렬(행이 열이 되고, 열이 행이되는)

array([[0, 2],
       [1, 3]])

In [46]:
np.linalg.inv(A)  # 역행렬

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [47]:
np.linalg.det(A)  # 행렬식

-2.0

## 3. 배열의 인덱싱 (배열의 위치나 조건을 지정해 배열의 원소 선택)

### 1) 1차원 배열

In [48]:
a1=np.array([0,10,20,30,40,50])   #1차원 배열 생성
a1

array([ 0, 10, 20, 30, 40, 50])

In [49]:
a1[4]     #배열명[위치]로 위치 지정
          #위치는 0부터 시작
          #a1배열에서 위치 0의 원소 선택

40

In [50]:
a1[5]=80    #원소값 변경 가능
a1

array([ 0, 10, 20, 30, 40, 80])

### 2) 1차원 배열에서 여러 원소 선택

In [51]:
a1[[1,3,4]]   #배열명[[위치1, 위치2, 위치3]]으로 여러 개 원소 선택
              #[1,3,4]리스트 삽입

array([10, 30, 40])

### 3) 2차원 배열

In [52]:
a2 = np.arange(10, 100, 10).reshape(3,3)    #2차원 배열 생성
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [53]:
a2[0, 2]     #배열명[행위치, 열위치]로 원소 선택
             #0행, 2열에 위치한 원소 선택

30

In [54]:
a2[2, 2] = 95    #원소 값 변경 가능
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [55]:
a2[1]     #행위치만을 지정하면 해당 행 전체 가져옴

array([40, 50, 60])

In [56]:
a2[1] = np.array([45, 55, 65])    #1행을 지정해 1행 전체 변경가능
                                  #np.array(seq_data)
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [57]:
a2[1] = [47, 57, 67]      #리스트만 이용해서도 행 전체 변경 가능
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

### 4) 2차원 배열에서 여러 원소 선택

In [58]:
a2[[0, 2], [0, 1]]    #2차원배열에서 여러 원소 선택
                      #배열명[[행위치1, 행위치2], [열위치1, 열위치2]]
                      #(o,o), (2,1) 선택

array([10, 80])

### 5) 배열에 조건을 지정해 해당 배열의 원소만 선택

In [59]:
a = np.array([1, 2, 3, 4, 5, 6])     #배열에 조건을 지정해 배열을 선택할 수 있음
                                     #배열명[조건]
a[a > 3]  

array([4, 5, 6])

In [60]:
a[(a % 2) == 0]   #짝수인 원소만 선택

array([2, 4, 6])

## 4. 배열의 슬라이싱 (범위를 지정해 배열 원소 선택)

### 1) 1차원 배열

In [61]:
b1 = np.array([0, 10, 20, 30, 40, 50])    
b1[1:4]     #배열[시작위치:끝위치]

array([10, 20, 30])

In [62]:
b1[:3]    #시작위치 지정안하면 0

array([ 0, 10, 20])

In [63]:
b1[2:]   #끝위치 지정안하면 그냥 배열의 끝까지

array([20, 30, 40, 50])

In [64]:
b1[2:5] = np.array([25, 35, 45])     #원소 변경 가능
b1

array([ 0, 10, 25, 35, 45, 50])

In [65]:
b1[3:6] = 60       #여러 원소를 같은 값으로 변경할떈 하나의 값을 지정
b1  

array([ 0, 10, 25, 60, 60, 60])

### 2) 2차원 배열

In [66]:
b2 = np.arange(10, 100, 10).reshape(3,3)    #2차원 배열 생성
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [67]:
b2[1:3, 1:3]    #배열[행 시작위치:행 끝위치, 열 시작위치:열 끝위치]
                #1~2행, 1열~2열

array([[50, 60],
       [80, 90]])

In [68]:
b2[:3, 1:]     #0행~2행, 1행~

array([[20, 30],
       [50, 60],
       [80, 90]])

In [69]:
b2[1][0:2]    #1행을 먼저 지정하고, 0열~1열에 대해 슬라이싱

array([40, 50])

In [70]:
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])    #값 변경
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])